name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  url_launcher: ^6.3.1
  syncfusion_flutter_gauges: ^29.1.40



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_start.png
    - assets/images/bg_start2.png
    - assets/images/bg_start3.png

  fonts:
    - family: 'Onest'
      fonts:
        - asset: assets/fonts/Onest-Light.ttf
          weight: 300
        - asset: assets/fonts/Onest-Regular.ttf
          weight: 400
        - asset: assets/fonts/Onest-Bold.ttf
          weight: 700